# Generated by Django 3.1.4 on 2021-01-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubers', '0003_auto_20210102_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtuber',
            name='age',
            field=models.IntegerField(default=23),
        ),
    ]
