# Generated by Django 3.1.5 on 2021-01-17 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiretubers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiretubers',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 17, 20, 23, 23, 149162)),
        ),
    ]
