# Generated by Django 3.1.5 on 2021-01-17 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiretubers', '0002_auto_20210117_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiretubers',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 17, 20, 34, 59, 941352)),
        ),
    ]
